name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-profile-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PROFILE_USER: theGoodB0rg
        run: python update-readme.py
      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- README.md; then
            git add README.md
            git commit -m "chore(profile): auto-update README based on achievements and stacks"
            git push
          else
            echo "No changes to commit"
          fi
